#!/bin/bash



xrandr --output VGA-1 --off --output LVDS-1 --primary --mode 1280x800 --pos 0x400 --rotate normal --output HDMI-3 --off --output HDMI-2 --off --output HDMI-1 --off --output DP-3 --off --output DP-2 --off --output DP-1 --mode 1440x900 --pos 1280x0 --rotate right

sleep 1

exec feh --bg-fill ~/.config/wallpapers/wallpaper3.jpg #wallpapers
