#!/bin/bash

getLayout() {

  xset -q | grep LED | awk '{ print $10 }'

}

if [[ $(getLayout) == "00000000"  ]] ||  [[ $(getLayout) == "00000001"  ]]; then 

  echo Us

elif [[ $(getLayout) == "00001000"  ]] || [[ $(getLayout) == "00001001"  ]]; then

  echo Ru

fi
